### ISSUE TITLE
Error output from freebox_

### ISSUE THREAD

**Issue by Owned67** [vadz/Munin-Plugin-Freebox#2]
Bonjour,

comment corriger cette erreur s'il te plaît :

> 2017/11/12-02:15:10 [700] Error output from freebox_:
> 2017/11/12-02:15:10 [700] 	Must be called freebox_{temp|bandwidth|freeplug|snr|fec|attn|switch1|switch2|switch3|switch4|uptime|multi}.
> 2017/11/12-02:15:10 [700] Service 'freebox_' exited with status 255/0.
> 2017/11/12-02:15:10 [700] Error output from freebox_:
> 2017/11/12-02:15:10 [700] 	Must be called freebox_{temp|bandwidth|freeplug|snr|fec|attn|switch1|switch2|switch3|switch4|uptime|multi}.
> 2017/11/12-02:15:10 [700] Service 'freebox_' exited with status 255/0.
> 2017/11/12-02:16:52 Server closing`

Merci

**Comment by vadz** [comment]
Désolé, mais ça ne fait vraiment pas de sens d'ouvrir les tickets ici pour une fork dont je ne sais absolument rien (son auteur ne m'avait jamais contacté ni même jugé utile de mentionner que son code est basé sur le mien, ce qui est assez sympa, en passant).

**Comment by Owned67** [comment]
Oui je viens d'y penser désolé... mais son fork en vaut la peine comparer au tien...

**Comment by Owned67** [comment]
Ceci dit, même avec ton script, c'est pareil lool

2017/11/15-00:40:02 [11729] Error output from freeboxv6:
2017/11/15-00:40:02 [11729] 	Can't locate WebService/Freebox.pm in @INC (you may need to install the WebService::Freebox module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /etc/munin/plugins/freeboxv6 line 79.
2017/11/15-00:40:02 [11729] 	BEGIN failed--compilation aborted at /etc/munin/plugins/freeboxv6 line 79.
2017/11/15-00:40:02 [11729] Service 'freeboxv6' exited with status 2/0.
2017/11/15-00:45:00 Server closing!
Process Backgrounded
2017/11/15-00:45:00 Munin::Node::Server (type Net::Server::Fork) starting! pid(13233)
Resolved [*]:4949 to [::]:4949, IPv6
Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
Binding to TCP port 4949 on host :: with IPv6
Setting gid to "0 0"
2017/11/15-00:45:01 [13233] Error output from freeboxv6:
2017/11/15-00:45:01 [13233] 	Must be called freebox_{temp|bandwidth|freeplug}.
2017/11/15-00:45:01 [13233] Service 'freeboxv6' exited with status 255/0.
2017/11/15-00:45:04 CONNECT TCP Peer: "[::ffff:127.0.0.1]:63221" Local: "[::ffff:127.0.0.1]:4949"
2017/11/15-00:45:08 [13521] Error output from freeboxv6:
2017/11/15-00:45:08 [13521] 	Must be called freebox_{temp|bandwidth|freeplug}.
2017/11/15-00:45:08 [13521] Service 'freeboxv6' exited with status 255/0.
2017/11/15-00:45:08 [13521] Error output from freeboxv6:
2017/11/15-00:45:08 [13521] 	Must be called freebox_{temp|bandwidth|freeplug}.
2017/11/15-00:45:08 [13521] Service 'freeboxv6' exited with status 255/0.
